### ISSUE TITLE
test2.p6 failure

### ISSUE THREAD

**Issue by molecules** [FCO/Test-Fuzz#1]
I love this module! Thanks for creating it.

However, I'm sorry to say that test2.p6 has errors. 

When I run

```
perl6 -Ilib test2.p6
```
I get the following error message:

```
Invocant requires an instance of type Test::Fuzz, but a type object was passed.  Did you forget a .new?
  in method run-tests at /group/ircf/cbottoms/Test-Fuzz/lib/Test/Fuzz.pm6 (Test::Fuzz) line 42
  in block <unit> at test2.p6 line 7

```

So, I modified the last line of test2.p6 to be the following:

```
Test::Fuzz.instance.run-tests;
```

And now it runs, but about 60-68 tests fail per run.

The last time I ran it, I tabulated the return values:

ten of the return values were `0`
five were `1`
five were `-1`
five were `3`
five were `-3`
five were `9999999999`
five were `-9999999999`
sixty were between `-9999999999` and `9999999999`

It looks like it is using `Int` instead of `Even` to generate test data.

I'm using Rakudo Star 2016.11 on 64-bit "CentOS Linux release 7.2.1511 (Core)".

**Comment by FCO** [comment]
Hi! Thanks for writing!
You are right! I forgot to update the test2 with the .instance.
But the test2 should fail... And yes, it should use Int to generate data... it receives Int and tries to return even. But not the square of every Int number is even, so that's the (proposital) error.
The repeated generated data is a real bug. When I run a generate-samples on Int sub-types, and that doesn't exist, it calls the Int's generate-samples... that's why it's duplicated.
Thank you very much for your message!
If ou liked the module, please take a look on the branch "role"... that will be the next version!

**Comment by FCO** [comment]
It's fixed on the "role" branch!

**Comment by molecules** [comment]
Thanks for working on this.

I'm getting a new error for `perl6 -Ilib test2.p6`:

```
No such method 'run-tests' for invocant of type 'Test::Fuzz'
  in block <unit> at test2.p6 line 7
```
I'm also getting a segmentation fault for `perl6 -Ilib test.p6`.

**Comment by FCO** [comment]
I fixed the test2.p6... The code of branch role exports the run-tests function... and there are no type Test::Fuzz.
The **segmentation fault** is a [rakudo/moarvm bug already reported](https://rt.perl.org/Public/Bug/Display.html?id=130379)
